Initial project setup
Alex-M-Markov/java-filmorate pull request #2
Opened 2022-04-26 22:32 UTC by Alex-M-Markov

2022-04-26 22:38 UTC, Alex-M-Markov commented
First version of the Filmorate application. Is able to receive, update and store in the memory users and films entities.

2022-04-27 15:56 UTC, kukolev requested changes

2022-04-27 15:56 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/validators/FilmDateValidator.java
> +    LocalDate firstFilm = LocalDate.of(1895, 12, 28);
Объект LocalDate.of(1895, 12, 28) лучше сделать константой, чтобы не приходилось всякий раз создавать при валидации.

2022-04-27 15:56 UTC, kukolev commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +	@Test
Нарушение кодстайла: Лишние отступы перед кодом. Советую в IDEA просто нажать комбинацию клавиш  Ctrl + Alt + L и код автоматически отформатируется.

2022-04-27 18:56 UTC, Alex-M-Markov commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +	@Test
Странно, в IDEA все выглядит отформатированным, Ctrl + Alt + L ни к каким изменениям не привёл. Обращу особое внимание на это при следующем коммите.

2022-04-27 18:57 UTC, Alex-M-Markov commented on src/main/java/ru/yandex/practicum/filmorate/validators/FilmDateValidator.java
> +    LocalDate firstFilm = LocalDate.of(1895, 12, 28);
Спасибо, исправил.

2022-04-27 19:06 UTC, Alex-M-Markov commented
All requested changes have been done

2022-04-28 16:14 UTC, kukolev commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +	@Test
Да, но при этом сам код пришел в норму. Полезно бывает проверять свой код прямо в инструменте для ревью, так можно увидеть то, что не заметно в IDEA.

2022-04-28 16:14 UTC, kukolev approved these changes

2022-05-06 13:28 UTC, merged