Add database
Alex-M-Markov/java-filmorate pull request #5
Opened 2022-06-21 15:58 UTC by Alex-M-Markov

feat: add DB repositories

2022-06-24 14:52 UTC, Alex-M-Markov commented
Четыре теста не работают. Марк подсказал, что они не относятся к 11-му спринту и были залиты позже. Поэтому сдаю работу с тем функционалом, который требовался по ТЗ.

2022-06-29 07:59 UTC, kukolev requested changes

2022-06-29 07:59 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +    public static final String CREATE_FILM = "insert into FILMS (NAME, DESCRIPTION, "
Константу нужно сделать приватной, т.к. она используется только в этом классе и не нужно, чтобы к ней был доступ извне.

Аналогичное замечание и к другим константам ниже.

2022-06-29 07:59 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/storage/GenreDbStorage.java
> +    public static final String GET_ALL_GENRES = "select * from Genre " +
Константу нужно сделать приватной, т.к. она используется только в этом классе и не нужно, чтобы к ней был доступ извне.

Аналогичное замечание и к другим константам ниже.

2022-06-29 07:59 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/storage/MpaDbStorage.java
> +    public static final String GET_ALL_MPAS = "select * from MPA_Rating";
Константу нужно сделать приватной, т.к. она используется только в этом классе и не нужно, чтобы к ней был доступ извне.

Аналогичное замечание и к другим константам ниже.

2022-06-29 07:59 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserDbStorage.java
> +                        /*  rs.getLong("User_ID"),*/
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-06-29 07:59 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserDbStorage.java
> +                        selectFriendship(rs.getLong("User_ID"))*/
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-06-29 07:59 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserDbStorage.java
> +                /*.filter(Friendship::isApproved)*/
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-06-29 07:59 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserDbStorage.java
> +                /* .filter(Friendship::isApproved)*/
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-06-29 07:59 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserDbStorage.java
> +    public static final String CREATE_USER = "insert into Users (Login, Name, Email, "
Константу нужно сделать приватной, т.к. она используется только в этом классе и не нужно, чтобы к ней был доступ извне.

Аналогично нужно поправить ниже.

2022-06-29 07:59 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserDbStorage.java
> +                        /*   .filter(Friendship::isApproved)*/
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-06-29 07:59 UTC, kukolev commented on src/test/java/ru/yandex/practicum/filmorate/UserDbStorageTests.java
> +/*
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

Вообще закомментированные тесты это плохая практика. Как правило это говорит о том, что тест не проходит и в программе есть ошибка. Если это так, то нужно раскомментировать тест и поправить код.

2022-06-29 17:01 UTC, kukolev approved these changes

2022-06-29 21:34 UTC, merged